hierarchy = {
  'cleaning_stuff': ['All-Purpose_Cleaners', 'Angle_Brooms', 'Bathroom_Cleaners', 'Broom_Handles_&_Heads', 'Brushes', 'Buckets', 'Caddies', 'Carpet_Cleaners', 'Carpet_Deodorizers', 'Carpet_Machine_Detergents', 'Carpet_Spot_Cleaning_Sprays', 'Carpet_Stain_Precleaners', 'Cloths_&_Wipes', 'Drain_Openers', 'Dustpans', 'Dust_Cloths', 'Dust_Mops_&_Pads', 'Feather_Dusters', 'Floor_Cleaners', 'Furniture_&_Wood_Polishes', 'Glass_Cleaners', 'Hand_Brooms', 'Kitchen_Cleaners', 'Latex_Gloves', 'Metal_Polishes', 'Mop_Handles', 'Mop_Heads_&_Sponges', 'Nitrile_Gloves', 'Paper_Towels', 'Push_Brooms', 'Refill_Sponges', 'Replacement_Heads', 'Sponges', 'Squeegees', 'Upholstery_Cleaners', 'Vinyl_Gloves', 'Wet_Mops'],
  'containers':     ['basket_container', 'colored_paper_bag', 'decorative_tray', 'disposable_container', 'food_banister', 'food_tray', 'glass_container', 'glass_food_container', 'glass_tray', 'grocery_bag', 'paper_bag', 'plastic_bag', 'plastic_container', 'plastic_food_container', 'plastic_tray', 'reusable_bag', 'serving_tray'],
  'cutlery':        ['butter_knives', 'cake_server', 'carving_knife_fork', 'chopsticks', 'dinnerware', 'Forks', 'Knives', 'plastic_fork', 'plastic_knife', 'plastic_spoon', 'serveware', 'Spoons', 'Sporks', 'steak_knives', 'utensils'],
  'drinks':         ['chocolate_drink_bottle', 'Cocoa_drink_bottle', 'Coffee_drink_bottle', 'Energy_Drink', 'Flavored_Water', 'iced_tea', 'Juice_bottle', 'juice_box', 'juice_carton', 'Mineral_Water', 'Seltzer_Water', 'soft_drink_bottle', 'Soft_Drink_can', 'Sparkling_Water', 'Sports_Drinking_Water', 'Tea_drink_bottle', 'Tonic_Water'],
  'food':           ['canned_sardines', 'canned_soup', 'canned_tuna', 'canned_vegetables', 'Cereals_box', 'Fruit_Butters', 'Honey', 'instant_ramen_noodles', 'instant_Soup', 'Jams', 'jarred_vegetables', 'Macaroni_&_Cheese_box', 'Marmalades', 'Muesli_box', 'noodle_soup_cup', 'Nut_&_Seed_Butter', 'Oatmeal_box', 'Olives_jar', 'Packaged_Bread', 'pasta_sides', 'pickled_vegetables', 'rice_sides'],
  'fruits':         ['Apples', 'Apricots', 'Bananas', 'Blueberries', 'Cherries', 'Cranberries', 'Figs', 'Grapefruit', 'Grapes', 'Lemons', 'Mangos', 'Melons', 'Mixed', 'Nectarines', 'Oranges', 'Papayas', 'Peaches', 'Pears', 'Pineapple', 'Plums', 'Raspberries', 'Strawberries', 'Tangerines'],
  'snacks':         ['Assorted_Snack_Cookies', 'Breadsticks', 'bubble_gum_brand', 'Candy_Bars', 'Chewing_Gum_brand', 'Cookies', 'Crackers', 'Fruit_Cups', 'Fruit_Snacks', 'Gummy_Candy_bag', 'Hard_Candy_snacks', 'Jelly_Beans_bag', 'Lollipops', 'Marshmallows_bag', 'Mints_bag', 'Nuts_snacks', 'Party_Mix_snack', 'Popcorn', 'Potato_Chips_bag', 'potato_chips_pringles', 'potato_Crisps', 'Pretzels', 'Puffed_Snacks', 'snacks_Seeds', 'Sour_Candy_bag', 'Vegetable_Chips_&_Crisps'],
  'tableware':      ['accent_plate', 'beer_glasses', 'buillin_cup', 'cereal_bowl', 'coffee_cup', 'coffee_mug', 'dessert_bowl', 'dessert_plate', 'dinner_plate', 'espresso_cup', 'fruit_plate', 'pasta_bowl', 'rice_bowl', 'salad_bowl', 'salad_plate', 'saucer_cup', 'side_dish_plate', 'snack_bowl', 'soup_bowl', 'sushi_plate', 'teacup', 'water_glasses', 'wine_glasses']
}